### ISSUE TITLE
Add End-To-End Testing for CineSimile

### ISSUE THREAD

**Issue by Niweera** [Niweera/cinesimile#12]
We need to add some test cases for the CineSimile ReactJS application. The following are our picks for suitable testing frameworks.

1. [Cypress](https://www.cypress.io/)
2. [Jest](https://jestjs.io/)
3. [Mocha](https://mochajs.org/)
4. [Jasmine](https://jasmine.github.io/)
5. [Puppeteer](https://pptr.dev/)

Out of these testing frameworks, we need to select one and add some test cases using it. As a contributor, you can comment on this issue about a suitable test framework and we will consider the most voted testing framework. Then you can start contributing to create test cases.

**Comment by abhinavjonnada82** [comment]
Jest..

**Comment by sumeetp4** [comment]
Cypress

**Comment by logesr** [comment]
Cypress

**Comment by VolatianaYuliana** [comment]
cypress

**Comment by Niweera** [comment]
Hmm. Seems many like Cypress. Let's see what others have to say. We'll wait until 5.00PM IST today.

**Comment by haseeb1009** [comment]
Jest

**Comment by aroojfatima41** [comment]
Jest

**Comment by SERPANT** [comment]
Jest

**Comment by Muhammad-Usman17** [comment]
Jest

**Comment by fathurifki** [comment]
Cypress

**Comment by peterver** [comment]
Jasmine in combination with puppeteer (Chrome Headless) and karma? :)

**Comment by zelaskov** [comment]
Cypress!

**Comment by saaheel** [comment]
Cypress

**Comment by Nikhil-dev13** [comment]
Jest

**Comment by Niweera** [comment]
Well, it seems Cypress is the winner. Let's go with Cypress then.

**Comment by Niweera** [comment]
@utkarsh4321 how about adding some Cypress Test cases?

**Comment by Pratyush-Khare** [comment]
Cypress

**Comment by nikhilchintawar** [comment]
jest

**Comment by basicallysteve** [comment]
Cypress

**Comment by yashrajb** [comment]
jest

**Comment by Niweera** [comment]
Thanks, guys for your votes. However, now the voting is closed 😁 and we have selected Cypress as the winner. No need to vote anymore from this point onwards. If you are willing to add some test cases using Cypress please let us know in the comments.

**Comment by SMAKSS** [comment]
@Niweera Well, I will be happy to write some tests with cypress for this repo. 😄

**Comment by saw-jan** [comment]
@Niweera I will initialize the cypress e2e test environment

**Comment by Niweera** [comment]
@saw-jan can initialize the Cypress e2e environment. After it is merged, @SMAKSS can write some test cases. I will assign you both to this task.

**Comment by sumeetp4** [comment]
@Niweera, Can I add some test cases once the e2e test environment is setup?

**Comment by Niweera** [comment]
@sumeetp4 yes you can. But to avoid merge conflicts let's wait until the environment is set up. I'll create new issues so that you can get assigned.

**Comment by SMAKSS** [comment]
@Niweera Should I start writing test cases? or you will create new issues for them (For distributing purposes)? 😄

**Comment by Niweera** [comment]
> @Niweera Should I start writing test cases? or you will create new issues for them (For distributing purposes)? 😄

I will create new issues and let you select one.
