### ISSUE TITLE
Redesign the Footer to be a sticky footer

### ISSUE THREAD

**Issue by Niweera** [Niweera/cinesimile#23]
As you can [see](https://simile.znbt.ml/), we currently have a relative footer. But to be more beautiful we would like to have a sticky footer. 

![image](https://user-images.githubusercontent.com/25348766/94917806-e499f080-04ce-11eb-9428-121cbd7182f9.png)

If you are interested in re-designing the footer to be a sticky footer, please let us know.

## What is a sticky footer? 🤷‍♂️

1. [CSS-Tricks Sticky Footer](https://css-tricks.com/couple-takes-sticky-footer/)
2. [Mozilla Developer Networks -Sticky footers](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers#:~:text=A%20sticky%20footer%20pattern%20is,shorter%20than%20the%20viewport%20height.)

PS: This issue is related to issue #4.

**Comment by jaspervhaastert** [comment]
I'd like to work on this :)

**Comment by Niweera** [comment]
Ah, nice. @jaspervhaastert I'll assign you to this task.

Remember to sync your fork by using the following command.

```shell
$ git pull upstream master
```
