### ISSUE TITLE
add contact page UI

### ISSUE THREAD

**Issue by saw-jan** [Niweera/cinesimile#39]
### Design contact page
- prototype or design image

Design code can be implemented by others.

**Comment by Niweera** [comment]
Hey @saw-jan, thank you for creating this issue! We will check this out...

**Comment by lokgubhaju** [comment]
maybe I'll work on it

**Comment by archisss** [comment]
what are you looking at the contact page a flat information o you need a form i can work on that but if you want a cohesive design you should start to approve the PR that you already have in the different parts of the project and then we can design a contact form

**Comment by utkarsh4321** [comment]
I wanna to do this
